FROM python:3.11-slim

WORKDIR /app

# 先复制依赖文件（利用 Docker 缓存层）
COPY requirements.txt .

COPY . .

# 暴露端口
EXPOSE 8000

# 加上 --trusted-host 忽略网络校验问题
RUN pip install --no-cache-dir -r requirements.txt --trusted-host pypi.org --trusted-host files.pythonhosted.org


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]